// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_unifi_dns_policy

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func UnifiDnsPolicyResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"dns_policy_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"enabled": schema.BoolAttribute{
				Required: true,
			},
			"site_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"type": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type UnifiDnsPolicyModel struct {
	DnsPolicyId types.String `tfsdk:"dns_policy_id"`
	Enabled     types.Bool   `tfsdk:"enabled"`
	SiteId      types.String `tfsdk:"site_id"`
	Type        types.String `tfsdk:"type"`
}
