// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_unifi_devices

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func UnifiDevicesDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"count": schema.Int64Attribute{
				Computed: true,
			},
			"data": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"features": schema.ListAttribute{
							ElementType: types.StringType,
							Computed:    true,
						},
						"firmware_updatable": schema.BoolAttribute{
							Computed: true,
						},
						"firmware_version": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.StringAttribute{
							Computed: true,
						},
						"interfaces": schema.ListAttribute{
							ElementType: types.StringType,
							Computed:    true,
						},
						"ip_address": schema.StringAttribute{
							Computed: true,
						},
						"mac_address": schema.StringAttribute{
							Computed: true,
						},
						"model": schema.StringAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"state": schema.StringAttribute{
							Computed: true,
						},
						"supported": schema.BoolAttribute{
							Computed: true,
						},
					},
					CustomType: DataType{
						ObjectType: types.ObjectType{
							AttrTypes: DataValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"filter": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"limit": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				Validators: []validator.Int64{
					int64validator.Between(0, 200),
				},
			},
			"offset": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
			},
			"site_id": schema.StringAttribute{
				Required: true,
			},
			"total_count": schema.Int64Attribute{
				Computed: true,
			},
		},
	}
}

type UnifiDevicesModel struct {
	Count      types.Int64  `tfsdk:"count"`
	Data       types.List   `tfsdk:"data"`
	Filter     types.String `tfsdk:"filter"`
	Limit      types.Int64  `tfsdk:"limit"`
	Offset     types.Int64  `tfsdk:"offset"`
	SiteId     types.String `tfsdk:"site_id"`
	TotalCount types.Int64  `tfsdk:"total_count"`
}

var _ basetypes.ObjectTypable = DataType{}

type DataType struct {
	basetypes.ObjectType
}

func (t DataType) Equal(o attr.Type) bool {
	other, ok := o.(DataType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DataType) String() string {
	return "DataType"
}

func (t DataType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	featuresAttribute, ok := attributes["features"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`features is missing from object`)

		return nil, diags
	}

	featuresVal, ok := featuresAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`features expected to be basetypes.ListValue, was: %T`, featuresAttribute))
	}

	firmwareUpdatableAttribute, ok := attributes["firmware_updatable"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`firmware_updatable is missing from object`)

		return nil, diags
	}

	firmwareUpdatableVal, ok := firmwareUpdatableAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`firmware_updatable expected to be basetypes.BoolValue, was: %T`, firmwareUpdatableAttribute))
	}

	firmwareVersionAttribute, ok := attributes["firmware_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`firmware_version is missing from object`)

		return nil, diags
	}

	firmwareVersionVal, ok := firmwareVersionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`firmware_version expected to be basetypes.StringValue, was: %T`, firmwareVersionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	interfacesAttribute, ok := attributes["interfaces"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`interfaces is missing from object`)

		return nil, diags
	}

	interfacesVal, ok := interfacesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`interfaces expected to be basetypes.ListValue, was: %T`, interfacesAttribute))
	}

	ipAddressAttribute, ok := attributes["ip_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_address is missing from object`)

		return nil, diags
	}

	ipAddressVal, ok := ipAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_address expected to be basetypes.StringValue, was: %T`, ipAddressAttribute))
	}

	macAddressAttribute, ok := attributes["mac_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`mac_address is missing from object`)

		return nil, diags
	}

	macAddressVal, ok := macAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`mac_address expected to be basetypes.StringValue, was: %T`, macAddressAttribute))
	}

	modelAttribute, ok := attributes["model"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`model is missing from object`)

		return nil, diags
	}

	modelVal, ok := modelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`model expected to be basetypes.StringValue, was: %T`, modelAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return nil, diags
	}

	stateVal, ok := stateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be basetypes.StringValue, was: %T`, stateAttribute))
	}

	supportedAttribute, ok := attributes["supported"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supported is missing from object`)

		return nil, diags
	}

	supportedVal, ok := supportedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supported expected to be basetypes.BoolValue, was: %T`, supportedAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DataValue{
		Features:          featuresVal,
		FirmwareUpdatable: firmwareUpdatableVal,
		FirmwareVersion:   firmwareVersionVal,
		Id:                idVal,
		Interfaces:        interfacesVal,
		IpAddress:         ipAddressVal,
		MacAddress:        macAddressVal,
		Model:             modelVal,
		Name:              nameVal,
		State:             stateVal,
		Supported:         supportedVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewDataValueNull() DataValue {
	return DataValue{
		state: attr.ValueStateNull,
	}
}

func NewDataValueUnknown() DataValue {
	return DataValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDataValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DataValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DataValue Attribute Value",
				"While creating a DataValue value, a missing attribute value was detected. "+
					"A DataValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DataValue Attribute Type",
				"While creating a DataValue value, an invalid attribute value was detected. "+
					"A DataValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DataValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DataValue Attribute Value",
				"While creating a DataValue value, an extra attribute value was detected. "+
					"A DataValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DataValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	featuresAttribute, ok := attributes["features"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`features is missing from object`)

		return NewDataValueUnknown(), diags
	}

	featuresVal, ok := featuresAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`features expected to be basetypes.ListValue, was: %T`, featuresAttribute))
	}

	firmwareUpdatableAttribute, ok := attributes["firmware_updatable"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`firmware_updatable is missing from object`)

		return NewDataValueUnknown(), diags
	}

	firmwareUpdatableVal, ok := firmwareUpdatableAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`firmware_updatable expected to be basetypes.BoolValue, was: %T`, firmwareUpdatableAttribute))
	}

	firmwareVersionAttribute, ok := attributes["firmware_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`firmware_version is missing from object`)

		return NewDataValueUnknown(), diags
	}

	firmwareVersionVal, ok := firmwareVersionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`firmware_version expected to be basetypes.StringValue, was: %T`, firmwareVersionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewDataValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	interfacesAttribute, ok := attributes["interfaces"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`interfaces is missing from object`)

		return NewDataValueUnknown(), diags
	}

	interfacesVal, ok := interfacesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`interfaces expected to be basetypes.ListValue, was: %T`, interfacesAttribute))
	}

	ipAddressAttribute, ok := attributes["ip_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_address is missing from object`)

		return NewDataValueUnknown(), diags
	}

	ipAddressVal, ok := ipAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_address expected to be basetypes.StringValue, was: %T`, ipAddressAttribute))
	}

	macAddressAttribute, ok := attributes["mac_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`mac_address is missing from object`)

		return NewDataValueUnknown(), diags
	}

	macAddressVal, ok := macAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`mac_address expected to be basetypes.StringValue, was: %T`, macAddressAttribute))
	}

	modelAttribute, ok := attributes["model"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`model is missing from object`)

		return NewDataValueUnknown(), diags
	}

	modelVal, ok := modelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`model expected to be basetypes.StringValue, was: %T`, modelAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewDataValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return NewDataValueUnknown(), diags
	}

	stateVal, ok := stateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be basetypes.StringValue, was: %T`, stateAttribute))
	}

	supportedAttribute, ok := attributes["supported"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supported is missing from object`)

		return NewDataValueUnknown(), diags
	}

	supportedVal, ok := supportedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supported expected to be basetypes.BoolValue, was: %T`, supportedAttribute))
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	return DataValue{
		Features:          featuresVal,
		FirmwareUpdatable: firmwareUpdatableVal,
		FirmwareVersion:   firmwareVersionVal,
		Id:                idVal,
		Interfaces:        interfacesVal,
		IpAddress:         ipAddressVal,
		MacAddress:        macAddressVal,
		Model:             modelVal,
		Name:              nameVal,
		State:             stateVal,
		Supported:         supportedVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewDataValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DataValue {
	object, diags := NewDataValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDataValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DataType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDataValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDataValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDataValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDataValueMust(DataValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DataType) ValueType(ctx context.Context) attr.Value {
	return DataValue{}
}

var _ basetypes.ObjectValuable = DataValue{}

type DataValue struct {
	Features          basetypes.ListValue   `tfsdk:"features"`
	FirmwareUpdatable basetypes.BoolValue   `tfsdk:"firmware_updatable"`
	FirmwareVersion   basetypes.StringValue `tfsdk:"firmware_version"`
	Id                basetypes.StringValue `tfsdk:"id"`
	Interfaces        basetypes.ListValue   `tfsdk:"interfaces"`
	IpAddress         basetypes.StringValue `tfsdk:"ip_address"`
	MacAddress        basetypes.StringValue `tfsdk:"mac_address"`
	Model             basetypes.StringValue `tfsdk:"model"`
	Name              basetypes.StringValue `tfsdk:"name"`
	State             basetypes.StringValue `tfsdk:"state"`
	Supported         basetypes.BoolValue   `tfsdk:"supported"`
	state             attr.ValueState
}

func (v DataValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 11)

	var val tftypes.Value
	var err error

	attrTypes["features"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["firmware_updatable"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["firmware_version"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["interfaces"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["ip_address"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["mac_address"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["model"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["state"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["supported"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 11)

		val, err = v.Features.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["features"] = val

		val, err = v.FirmwareUpdatable.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["firmware_updatable"] = val

		val, err = v.FirmwareVersion.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["firmware_version"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Interfaces.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["interfaces"] = val

		val, err = v.IpAddress.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip_address"] = val

		val, err = v.MacAddress.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["mac_address"] = val

		val, err = v.Model.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["model"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.State.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["state"] = val

		val, err = v.Supported.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supported"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DataValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DataValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DataValue) String() string {
	return "DataValue"
}

func (v DataValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var featuresVal basetypes.ListValue
	switch {
	case v.Features.IsUnknown():
		featuresVal = types.ListUnknown(types.StringType)
	case v.Features.IsNull():
		featuresVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		featuresVal, d = types.ListValue(types.StringType, v.Features.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"features": basetypes.ListType{
				ElemType: types.StringType,
			},
			"firmware_updatable": basetypes.BoolType{},
			"firmware_version":   basetypes.StringType{},
			"id":                 basetypes.StringType{},
			"interfaces": basetypes.ListType{
				ElemType: types.StringType,
			},
			"ip_address":  basetypes.StringType{},
			"mac_address": basetypes.StringType{},
			"model":       basetypes.StringType{},
			"name":        basetypes.StringType{},
			"state":       basetypes.StringType{},
			"supported":   basetypes.BoolType{},
		}), diags
	}

	var interfacesVal basetypes.ListValue
	switch {
	case v.Interfaces.IsUnknown():
		interfacesVal = types.ListUnknown(types.StringType)
	case v.Interfaces.IsNull():
		interfacesVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		interfacesVal, d = types.ListValue(types.StringType, v.Interfaces.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"features": basetypes.ListType{
				ElemType: types.StringType,
			},
			"firmware_updatable": basetypes.BoolType{},
			"firmware_version":   basetypes.StringType{},
			"id":                 basetypes.StringType{},
			"interfaces": basetypes.ListType{
				ElemType: types.StringType,
			},
			"ip_address":  basetypes.StringType{},
			"mac_address": basetypes.StringType{},
			"model":       basetypes.StringType{},
			"name":        basetypes.StringType{},
			"state":       basetypes.StringType{},
			"supported":   basetypes.BoolType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"features": basetypes.ListType{
			ElemType: types.StringType,
		},
		"firmware_updatable": basetypes.BoolType{},
		"firmware_version":   basetypes.StringType{},
		"id":                 basetypes.StringType{},
		"interfaces": basetypes.ListType{
			ElemType: types.StringType,
		},
		"ip_address":  basetypes.StringType{},
		"mac_address": basetypes.StringType{},
		"model":       basetypes.StringType{},
		"name":        basetypes.StringType{},
		"state":       basetypes.StringType{},
		"supported":   basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"features":           featuresVal,
			"firmware_updatable": v.FirmwareUpdatable,
			"firmware_version":   v.FirmwareVersion,
			"id":                 v.Id,
			"interfaces":         interfacesVal,
			"ip_address":         v.IpAddress,
			"mac_address":        v.MacAddress,
			"model":              v.Model,
			"name":               v.Name,
			"state":              v.State,
			"supported":          v.Supported,
		})

	return objVal, diags
}

func (v DataValue) Equal(o attr.Value) bool {
	other, ok := o.(DataValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Features.Equal(other.Features) {
		return false
	}

	if !v.FirmwareUpdatable.Equal(other.FirmwareUpdatable) {
		return false
	}

	if !v.FirmwareVersion.Equal(other.FirmwareVersion) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Interfaces.Equal(other.Interfaces) {
		return false
	}

	if !v.IpAddress.Equal(other.IpAddress) {
		return false
	}

	if !v.MacAddress.Equal(other.MacAddress) {
		return false
	}

	if !v.Model.Equal(other.Model) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.State.Equal(other.State) {
		return false
	}

	if !v.Supported.Equal(other.Supported) {
		return false
	}

	return true
}

func (v DataValue) Type(ctx context.Context) attr.Type {
	return DataType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DataValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"features": basetypes.ListType{
			ElemType: types.StringType,
		},
		"firmware_updatable": basetypes.BoolType{},
		"firmware_version":   basetypes.StringType{},
		"id":                 basetypes.StringType{},
		"interfaces": basetypes.ListType{
			ElemType: types.StringType,
		},
		"ip_address":  basetypes.StringType{},
		"mac_address": basetypes.StringType{},
		"model":       basetypes.StringType{},
		"name":        basetypes.StringType{},
		"state":       basetypes.StringType{},
		"supported":   basetypes.BoolType{},
	}
}
