// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_unifi_network

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func UnifiNetworkResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"default": schema.BoolAttribute{
				Computed: true,
			},
			"dhcp_guarding": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"trusted_dhcp_server_ip_addresses": schema.ListAttribute{
						ElementType:         types.StringType,
						Required:            true,
						Description:         "List of trusted DHCP server IP addresses.",
						MarkdownDescription: "List of trusted DHCP server IP addresses.",
						Validators: []validator.List{
							listvalidator.SizeAtLeast(1),
						},
					},
				},
				CustomType: DhcpGuardingType{
					ObjectType: types.ObjectType{
						AttrTypes: DhcpGuardingValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Details about DHCP Guarding settings for this Network.",
				MarkdownDescription: "Details about DHCP Guarding settings for this Network.",
			},
			"enabled": schema.BoolAttribute{
				Required: true,
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"management": schema.StringAttribute{
				Required: true,
			},
			"metadata": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"origin": schema.StringAttribute{
						Computed: true,
					},
				},
				CustomType: MetadataType{
					ObjectType: types.ObjectType{
						AttrTypes: MetadataValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"network_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"site_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"vlan_id": schema.Int64Attribute{
				Required:            true,
				Description:         "VLAN ID. Must be 1 for the default network and >= 2 for additional networks.",
				MarkdownDescription: "VLAN ID. Must be 1 for the default network and >= 2 for additional networks.",
				Validators: []validator.Int64{
					int64validator.Between(1, 4009),
				},
			},
		},
	}
}

type UnifiNetworkModel struct {
	Default      types.Bool        `tfsdk:"default"`
	DhcpGuarding DhcpGuardingValue `tfsdk:"dhcp_guarding"`
	Enabled      types.Bool        `tfsdk:"enabled"`
	Id           types.String      `tfsdk:"id"`
	Management   types.String      `tfsdk:"management"`
	Metadata     MetadataValue     `tfsdk:"metadata"`
	Name         types.String      `tfsdk:"name"`
	NetworkId    types.String      `tfsdk:"network_id"`
	SiteId       types.String      `tfsdk:"site_id"`
	VlanId       types.Int64       `tfsdk:"vlan_id"`
}

var _ basetypes.ObjectTypable = DhcpGuardingType{}

type DhcpGuardingType struct {
	basetypes.ObjectType
}

func (t DhcpGuardingType) Equal(o attr.Type) bool {
	other, ok := o.(DhcpGuardingType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DhcpGuardingType) String() string {
	return "DhcpGuardingType"
}

func (t DhcpGuardingType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	trustedDhcpServerIpAddressesAttribute, ok := attributes["trusted_dhcp_server_ip_addresses"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`trusted_dhcp_server_ip_addresses is missing from object`)

		return nil, diags
	}

	trustedDhcpServerIpAddressesVal, ok := trustedDhcpServerIpAddressesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`trusted_dhcp_server_ip_addresses expected to be basetypes.ListValue, was: %T`, trustedDhcpServerIpAddressesAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DhcpGuardingValue{
		TrustedDhcpServerIpAddresses: trustedDhcpServerIpAddressesVal,
		state:                        attr.ValueStateKnown,
	}, diags
}

func NewDhcpGuardingValueNull() DhcpGuardingValue {
	return DhcpGuardingValue{
		state: attr.ValueStateNull,
	}
}

func NewDhcpGuardingValueUnknown() DhcpGuardingValue {
	return DhcpGuardingValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDhcpGuardingValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DhcpGuardingValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DhcpGuardingValue Attribute Value",
				"While creating a DhcpGuardingValue value, a missing attribute value was detected. "+
					"A DhcpGuardingValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DhcpGuardingValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DhcpGuardingValue Attribute Type",
				"While creating a DhcpGuardingValue value, an invalid attribute value was detected. "+
					"A DhcpGuardingValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DhcpGuardingValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DhcpGuardingValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DhcpGuardingValue Attribute Value",
				"While creating a DhcpGuardingValue value, an extra attribute value was detected. "+
					"A DhcpGuardingValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DhcpGuardingValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDhcpGuardingValueUnknown(), diags
	}

	trustedDhcpServerIpAddressesAttribute, ok := attributes["trusted_dhcp_server_ip_addresses"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`trusted_dhcp_server_ip_addresses is missing from object`)

		return NewDhcpGuardingValueUnknown(), diags
	}

	trustedDhcpServerIpAddressesVal, ok := trustedDhcpServerIpAddressesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`trusted_dhcp_server_ip_addresses expected to be basetypes.ListValue, was: %T`, trustedDhcpServerIpAddressesAttribute))
	}

	if diags.HasError() {
		return NewDhcpGuardingValueUnknown(), diags
	}

	return DhcpGuardingValue{
		TrustedDhcpServerIpAddresses: trustedDhcpServerIpAddressesVal,
		state:                        attr.ValueStateKnown,
	}, diags
}

func NewDhcpGuardingValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DhcpGuardingValue {
	object, diags := NewDhcpGuardingValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDhcpGuardingValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DhcpGuardingType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDhcpGuardingValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDhcpGuardingValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDhcpGuardingValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDhcpGuardingValueMust(DhcpGuardingValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DhcpGuardingType) ValueType(ctx context.Context) attr.Value {
	return DhcpGuardingValue{}
}

var _ basetypes.ObjectValuable = DhcpGuardingValue{}

type DhcpGuardingValue struct {
	TrustedDhcpServerIpAddresses basetypes.ListValue `tfsdk:"trusted_dhcp_server_ip_addresses"`
	state                        attr.ValueState
}

func (v DhcpGuardingValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["trusted_dhcp_server_ip_addresses"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.TrustedDhcpServerIpAddresses.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["trusted_dhcp_server_ip_addresses"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DhcpGuardingValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DhcpGuardingValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DhcpGuardingValue) String() string {
	return "DhcpGuardingValue"
}

func (v DhcpGuardingValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var trustedDhcpServerIpAddressesVal basetypes.ListValue
	switch {
	case v.TrustedDhcpServerIpAddresses.IsUnknown():
		trustedDhcpServerIpAddressesVal = types.ListUnknown(types.StringType)
	case v.TrustedDhcpServerIpAddresses.IsNull():
		trustedDhcpServerIpAddressesVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		trustedDhcpServerIpAddressesVal, d = types.ListValue(types.StringType, v.TrustedDhcpServerIpAddresses.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"trusted_dhcp_server_ip_addresses": basetypes.ListType{
				ElemType: types.StringType,
			},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"trusted_dhcp_server_ip_addresses": basetypes.ListType{
			ElemType: types.StringType,
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"trusted_dhcp_server_ip_addresses": trustedDhcpServerIpAddressesVal,
		})

	return objVal, diags
}

func (v DhcpGuardingValue) Equal(o attr.Value) bool {
	other, ok := o.(DhcpGuardingValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.TrustedDhcpServerIpAddresses.Equal(other.TrustedDhcpServerIpAddresses) {
		return false
	}

	return true
}

func (v DhcpGuardingValue) Type(ctx context.Context) attr.Type {
	return DhcpGuardingType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DhcpGuardingValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"trusted_dhcp_server_ip_addresses": basetypes.ListType{
			ElemType: types.StringType,
		},
	}
}

var _ basetypes.ObjectTypable = MetadataType{}

type MetadataType struct {
	basetypes.ObjectType
}

func (t MetadataType) Equal(o attr.Type) bool {
	other, ok := o.(MetadataType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MetadataType) String() string {
	return "MetadataType"
}

func (t MetadataType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	originAttribute, ok := attributes["origin"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`origin is missing from object`)

		return nil, diags
	}

	originVal, ok := originAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`origin expected to be basetypes.StringValue, was: %T`, originAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return MetadataValue{
		Origin: originVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewMetadataValueNull() MetadataValue {
	return MetadataValue{
		state: attr.ValueStateNull,
	}
}

func NewMetadataValueUnknown() MetadataValue {
	return MetadataValue{
		state: attr.ValueStateUnknown,
	}
}

func NewMetadataValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MetadataValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MetadataValue Attribute Value",
				"While creating a MetadataValue value, a missing attribute value was detected. "+
					"A MetadataValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetadataValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MetadataValue Attribute Type",
				"While creating a MetadataValue value, an invalid attribute value was detected. "+
					"A MetadataValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetadataValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MetadataValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MetadataValue Attribute Value",
				"While creating a MetadataValue value, an extra attribute value was detected. "+
					"A MetadataValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MetadataValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewMetadataValueUnknown(), diags
	}

	originAttribute, ok := attributes["origin"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`origin is missing from object`)

		return NewMetadataValueUnknown(), diags
	}

	originVal, ok := originAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`origin expected to be basetypes.StringValue, was: %T`, originAttribute))
	}

	if diags.HasError() {
		return NewMetadataValueUnknown(), diags
	}

	return MetadataValue{
		Origin: originVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewMetadataValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MetadataValue {
	object, diags := NewMetadataValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewMetadataValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MetadataType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewMetadataValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewMetadataValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMetadataValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewMetadataValueMust(MetadataValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MetadataType) ValueType(ctx context.Context) attr.Value {
	return MetadataValue{}
}

var _ basetypes.ObjectValuable = MetadataValue{}

type MetadataValue struct {
	Origin basetypes.StringValue `tfsdk:"origin"`
	state  attr.ValueState
}

func (v MetadataValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["origin"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Origin.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["origin"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MetadataValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MetadataValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MetadataValue) String() string {
	return "MetadataValue"
}

func (v MetadataValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"origin": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"origin": v.Origin,
		})

	return objVal, diags
}

func (v MetadataValue) Equal(o attr.Value) bool {
	other, ok := o.(MetadataValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Origin.Equal(other.Origin) {
		return false
	}

	return true
}

func (v MetadataValue) Type(ctx context.Context) attr.Type {
	return MetadataType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MetadataValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"origin": basetypes.StringType{},
	}
}
