// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_unifi_traffic_matching_list

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func UnifiTrafficMatchingListResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
			"site_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"traffic_matching_list_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"type": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type UnifiTrafficMatchingListModel struct {
	Id                    types.String `tfsdk:"id"`
	Name                  types.String `tfsdk:"name"`
	SiteId                types.String `tfsdk:"site_id"`
	TrafficMatchingListId types.String `tfsdk:"traffic_matching_list_id"`
	Type                  types.String `tfsdk:"type"`
}
