// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_unifi_firewall_policy

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func UnifiFirewallPolicyResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"action": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"type": schema.StringAttribute{
						Required: true,
					},
				},
				CustomType: ActionType{
					ObjectType: types.ObjectType{
						AttrTypes: ActionValue{}.AttributeTypes(ctx),
					},
				},
				Required:            true,
				Description:         "Defines action for matched traffic.",
				MarkdownDescription: "Defines action for matched traffic.",
			},
			"connection_state_filter": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Match on firewall connection state. If null, matches all connection states.",
				MarkdownDescription: "Match on firewall connection state. If null, matches all connection states.",
				Validators: []validator.List{
					listvalidator.SizeBetween(1, 2147483647),
					listvalidator.UniqueValues(),
				},
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"destination": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"traffic_filter": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"type": schema.StringAttribute{
								Required: true,
							},
						},
						CustomType: TrafficFilterType{
							ObjectType: types.ObjectType{
								AttrTypes: TrafficFilterValue{}.AttributeTypes(ctx),
							},
						},
						Optional: true,
						Computed: true,
					},
					"zone_id": schema.StringAttribute{
						Required:            true,
						Description:         "ID of the firewall zone to which the matched traffic is destined.",
						MarkdownDescription: "ID of the firewall zone to which the matched traffic is destined.",
					},
				},
				CustomType: DestinationType{
					ObjectType: types.ObjectType{
						AttrTypes: DestinationValue{}.AttributeTypes(ctx),
					},
				},
				Required: true,
			},
			"enabled": schema.BoolAttribute{
				Required: true,
			},
			"firewall_policy_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"index": schema.Int64Attribute{
				Computed: true,
			},
			"ip_protocol_scope": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"ip_version": schema.StringAttribute{
						Required: true,
					},
				},
				CustomType: IpProtocolScopeType{
					ObjectType: types.ObjectType{
						AttrTypes: IpProtocolScopeValue{}.AttributeTypes(ctx),
					},
				},
				Required:            true,
				Description:         "Defines rules for matching by IP version and protocol.",
				MarkdownDescription: "Defines rules for matching by IP version and protocol.",
			},
			"ipsec_filter": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Match on traffic encrypted, or not encrypted by IPsec. If null, matches all traffic.",
				MarkdownDescription: "Match on traffic encrypted, or not encrypted by IPsec. If null, matches all traffic.",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"MATCH_ENCRYPTED",
						"MATCH_NOT_ENCRYPTED",
					),
				},
			},
			"logging_enabled": schema.BoolAttribute{
				Required:            true,
				Description:         "Generate syslog entries when traffic is matched. Such entries are sent to a remote syslog server.",
				MarkdownDescription: "Generate syslog entries when traffic is matched. Such entries are sent to a remote syslog server.",
			},
			"metadata": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"origin": schema.StringAttribute{
						Computed: true,
					},
				},
				CustomType: MetadataType{
					ObjectType: types.ObjectType{
						AttrTypes: MetadataValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
			"schedule": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"mode": schema.StringAttribute{
						Required: true,
					},
				},
				CustomType: ScheduleType{
					ObjectType: types.ObjectType{
						AttrTypes: ScheduleValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Defines date and time when the entity is active. If null, the entity is always active.",
				MarkdownDescription: "Defines date and time when the entity is active. If null, the entity is always active.",
			},
			"site_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"source": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"traffic_filter": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"type": schema.StringAttribute{
								Required: true,
							},
						},
						CustomType: TrafficFilterType{
							ObjectType: types.ObjectType{
								AttrTypes: TrafficFilterValue{}.AttributeTypes(ctx),
							},
						},
						Optional: true,
						Computed: true,
					},
					"zone_id": schema.StringAttribute{
						Required:            true,
						Description:         "ID of the firewall zone from which the matched traffic originates.",
						MarkdownDescription: "ID of the firewall zone from which the matched traffic originates.",
					},
				},
				CustomType: SourceType{
					ObjectType: types.ObjectType{
						AttrTypes: SourceValue{}.AttributeTypes(ctx),
					},
				},
				Required: true,
			},
		},
	}
}

type UnifiFirewallPolicyModel struct {
	Action                ActionValue          `tfsdk:"action"`
	ConnectionStateFilter types.List           `tfsdk:"connection_state_filter"`
	Description           types.String         `tfsdk:"description"`
	Destination           DestinationValue     `tfsdk:"destination"`
	Enabled               types.Bool           `tfsdk:"enabled"`
	FirewallPolicyId      types.String         `tfsdk:"firewall_policy_id"`
	Id                    types.String         `tfsdk:"id"`
	Index                 types.Int64          `tfsdk:"index"`
	IpProtocolScope       IpProtocolScopeValue `tfsdk:"ip_protocol_scope"`
	IpsecFilter           types.String         `tfsdk:"ipsec_filter"`
	LoggingEnabled        types.Bool           `tfsdk:"logging_enabled"`
	Metadata              MetadataValue        `tfsdk:"metadata"`
	Name                  types.String         `tfsdk:"name"`
	Schedule              ScheduleValue        `tfsdk:"schedule"`
	SiteId                types.String         `tfsdk:"site_id"`
	Source                SourceValue          `tfsdk:"source"`
}

var _ basetypes.ObjectTypable = ActionType{}

type ActionType struct {
	basetypes.ObjectType
}

func (t ActionType) Equal(o attr.Type) bool {
	other, ok := o.(ActionType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ActionType) String() string {
	return "ActionType"
}

func (t ActionType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ActionValue{
		ActionType: typeVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewActionValueNull() ActionValue {
	return ActionValue{
		state: attr.ValueStateNull,
	}
}

func NewActionValueUnknown() ActionValue {
	return ActionValue{
		state: attr.ValueStateUnknown,
	}
}

func NewActionValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ActionValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ActionValue Attribute Value",
				"While creating a ActionValue value, a missing attribute value was detected. "+
					"A ActionValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ActionValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ActionValue Attribute Type",
				"While creating a ActionValue value, an invalid attribute value was detected. "+
					"A ActionValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ActionValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ActionValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ActionValue Attribute Value",
				"While creating a ActionValue value, an extra attribute value was detected. "+
					"A ActionValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ActionValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewActionValueUnknown(), diags
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewActionValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewActionValueUnknown(), diags
	}

	return ActionValue{
		ActionType: typeVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewActionValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ActionValue {
	object, diags := NewActionValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewActionValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ActionType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewActionValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewActionValueUnknown(), nil
	}

	if in.IsNull() {
		return NewActionValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewActionValueMust(ActionValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ActionType) ValueType(ctx context.Context) attr.Value {
	return ActionValue{}
}

var _ basetypes.ObjectValuable = ActionValue{}

type ActionValue struct {
	ActionType basetypes.StringValue `tfsdk:"type"`
	state      attr.ValueState
}

func (v ActionValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.ActionType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ActionValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ActionValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ActionValue) String() string {
	return "ActionValue"
}

func (v ActionValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"type": v.ActionType,
		})

	return objVal, diags
}

func (v ActionValue) Equal(o attr.Value) bool {
	other, ok := o.(ActionValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ActionType.Equal(other.ActionType) {
		return false
	}

	return true
}

func (v ActionValue) Type(ctx context.Context) attr.Type {
	return ActionType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ActionValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"type": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = DestinationType{}

type DestinationType struct {
	basetypes.ObjectType
}

func (t DestinationType) Equal(o attr.Type) bool {
	other, ok := o.(DestinationType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DestinationType) String() string {
	return "DestinationType"
}

func (t DestinationType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	trafficFilterAttribute, ok := attributes["traffic_filter"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`traffic_filter is missing from object`)

		return nil, diags
	}

	trafficFilterVal, ok := trafficFilterAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`traffic_filter expected to be basetypes.ObjectValue, was: %T`, trafficFilterAttribute))
	}

	zoneIdAttribute, ok := attributes["zone_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zone_id is missing from object`)

		return nil, diags
	}

	zoneIdVal, ok := zoneIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zone_id expected to be basetypes.StringValue, was: %T`, zoneIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DestinationValue{
		TrafficFilter: trafficFilterVal,
		ZoneId:        zoneIdVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewDestinationValueNull() DestinationValue {
	return DestinationValue{
		state: attr.ValueStateNull,
	}
}

func NewDestinationValueUnknown() DestinationValue {
	return DestinationValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDestinationValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DestinationValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DestinationValue Attribute Value",
				"While creating a DestinationValue value, a missing attribute value was detected. "+
					"A DestinationValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DestinationValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DestinationValue Attribute Type",
				"While creating a DestinationValue value, an invalid attribute value was detected. "+
					"A DestinationValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DestinationValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DestinationValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DestinationValue Attribute Value",
				"While creating a DestinationValue value, an extra attribute value was detected. "+
					"A DestinationValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DestinationValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDestinationValueUnknown(), diags
	}

	trafficFilterAttribute, ok := attributes["traffic_filter"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`traffic_filter is missing from object`)

		return NewDestinationValueUnknown(), diags
	}

	trafficFilterVal, ok := trafficFilterAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`traffic_filter expected to be basetypes.ObjectValue, was: %T`, trafficFilterAttribute))
	}

	zoneIdAttribute, ok := attributes["zone_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zone_id is missing from object`)

		return NewDestinationValueUnknown(), diags
	}

	zoneIdVal, ok := zoneIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zone_id expected to be basetypes.StringValue, was: %T`, zoneIdAttribute))
	}

	if diags.HasError() {
		return NewDestinationValueUnknown(), diags
	}

	return DestinationValue{
		TrafficFilter: trafficFilterVal,
		ZoneId:        zoneIdVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewDestinationValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DestinationValue {
	object, diags := NewDestinationValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDestinationValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DestinationType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDestinationValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDestinationValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDestinationValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDestinationValueMust(DestinationValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DestinationType) ValueType(ctx context.Context) attr.Value {
	return DestinationValue{}
}

var _ basetypes.ObjectValuable = DestinationValue{}

type DestinationValue struct {
	TrafficFilter basetypes.ObjectValue `tfsdk:"traffic_filter"`
	ZoneId        basetypes.StringValue `tfsdk:"zone_id"`
	state         attr.ValueState
}

func (v DestinationValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["traffic_filter"] = basetypes.ObjectType{
		AttrTypes: TrafficFilterValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["zone_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.TrafficFilter.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["traffic_filter"] = val

		val, err = v.ZoneId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["zone_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DestinationValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DestinationValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DestinationValue) String() string {
	return "DestinationValue"
}

func (v DestinationValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var trafficFilter basetypes.ObjectValue

	if v.TrafficFilter.IsNull() {
		trafficFilter = types.ObjectNull(
			TrafficFilterValue{}.AttributeTypes(ctx),
		)
	}

	if v.TrafficFilter.IsUnknown() {
		trafficFilter = types.ObjectUnknown(
			TrafficFilterValue{}.AttributeTypes(ctx),
		)
	}

	if !v.TrafficFilter.IsNull() && !v.TrafficFilter.IsUnknown() {
		trafficFilter = types.ObjectValueMust(
			TrafficFilterValue{}.AttributeTypes(ctx),
			v.TrafficFilter.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"traffic_filter": basetypes.ObjectType{
			AttrTypes: TrafficFilterValue{}.AttributeTypes(ctx),
		},
		"zone_id": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"traffic_filter": trafficFilter,
			"zone_id":        v.ZoneId,
		})

	return objVal, diags
}

func (v DestinationValue) Equal(o attr.Value) bool {
	other, ok := o.(DestinationValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.TrafficFilter.Equal(other.TrafficFilter) {
		return false
	}

	if !v.ZoneId.Equal(other.ZoneId) {
		return false
	}

	return true
}

func (v DestinationValue) Type(ctx context.Context) attr.Type {
	return DestinationType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DestinationValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"traffic_filter": basetypes.ObjectType{
			AttrTypes: TrafficFilterValue{}.AttributeTypes(ctx),
		},
		"zone_id": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = TrafficFilterType{}

type TrafficFilterType struct {
	basetypes.ObjectType
}

func (t TrafficFilterType) Equal(o attr.Type) bool {
	other, ok := o.(TrafficFilterType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TrafficFilterType) String() string {
	return "TrafficFilterType"
}

func (t TrafficFilterType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TrafficFilterValue{
		TrafficFilterType: typeVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewTrafficFilterValueNull() TrafficFilterValue {
	return TrafficFilterValue{
		state: attr.ValueStateNull,
	}
}

func NewTrafficFilterValueUnknown() TrafficFilterValue {
	return TrafficFilterValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTrafficFilterValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TrafficFilterValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TrafficFilterValue Attribute Value",
				"While creating a TrafficFilterValue value, a missing attribute value was detected. "+
					"A TrafficFilterValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TrafficFilterValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TrafficFilterValue Attribute Type",
				"While creating a TrafficFilterValue value, an invalid attribute value was detected. "+
					"A TrafficFilterValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TrafficFilterValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TrafficFilterValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TrafficFilterValue Attribute Value",
				"While creating a TrafficFilterValue value, an extra attribute value was detected. "+
					"A TrafficFilterValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TrafficFilterValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTrafficFilterValueUnknown(), diags
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewTrafficFilterValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewTrafficFilterValueUnknown(), diags
	}

	return TrafficFilterValue{
		TrafficFilterType: typeVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewTrafficFilterValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TrafficFilterValue {
	object, diags := NewTrafficFilterValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTrafficFilterValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TrafficFilterType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTrafficFilterValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTrafficFilterValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTrafficFilterValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTrafficFilterValueMust(TrafficFilterValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TrafficFilterType) ValueType(ctx context.Context) attr.Value {
	return TrafficFilterValue{}
}

var _ basetypes.ObjectValuable = TrafficFilterValue{}

type TrafficFilterValue struct {
	TrafficFilterType basetypes.StringValue `tfsdk:"type"`
	state             attr.ValueState
}

func (v TrafficFilterValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.TrafficFilterType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TrafficFilterValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TrafficFilterValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TrafficFilterValue) String() string {
	return "TrafficFilterValue"
}

func (v TrafficFilterValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"type": v.TrafficFilterType,
		})

	return objVal, diags
}

func (v TrafficFilterValue) Equal(o attr.Value) bool {
	other, ok := o.(TrafficFilterValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.TrafficFilterType.Equal(other.TrafficFilterType) {
		return false
	}

	return true
}

func (v TrafficFilterValue) Type(ctx context.Context) attr.Type {
	return TrafficFilterType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TrafficFilterValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"type": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = IpProtocolScopeType{}

type IpProtocolScopeType struct {
	basetypes.ObjectType
}

func (t IpProtocolScopeType) Equal(o attr.Type) bool {
	other, ok := o.(IpProtocolScopeType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t IpProtocolScopeType) String() string {
	return "IpProtocolScopeType"
}

func (t IpProtocolScopeType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	ipVersionAttribute, ok := attributes["ip_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_version is missing from object`)

		return nil, diags
	}

	ipVersionVal, ok := ipVersionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_version expected to be basetypes.StringValue, was: %T`, ipVersionAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return IpProtocolScopeValue{
		IpVersion: ipVersionVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewIpProtocolScopeValueNull() IpProtocolScopeValue {
	return IpProtocolScopeValue{
		state: attr.ValueStateNull,
	}
}

func NewIpProtocolScopeValueUnknown() IpProtocolScopeValue {
	return IpProtocolScopeValue{
		state: attr.ValueStateUnknown,
	}
}

func NewIpProtocolScopeValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (IpProtocolScopeValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing IpProtocolScopeValue Attribute Value",
				"While creating a IpProtocolScopeValue value, a missing attribute value was detected. "+
					"A IpProtocolScopeValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IpProtocolScopeValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid IpProtocolScopeValue Attribute Type",
				"While creating a IpProtocolScopeValue value, an invalid attribute value was detected. "+
					"A IpProtocolScopeValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IpProtocolScopeValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("IpProtocolScopeValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra IpProtocolScopeValue Attribute Value",
				"While creating a IpProtocolScopeValue value, an extra attribute value was detected. "+
					"A IpProtocolScopeValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra IpProtocolScopeValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewIpProtocolScopeValueUnknown(), diags
	}

	ipVersionAttribute, ok := attributes["ip_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_version is missing from object`)

		return NewIpProtocolScopeValueUnknown(), diags
	}

	ipVersionVal, ok := ipVersionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_version expected to be basetypes.StringValue, was: %T`, ipVersionAttribute))
	}

	if diags.HasError() {
		return NewIpProtocolScopeValueUnknown(), diags
	}

	return IpProtocolScopeValue{
		IpVersion: ipVersionVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewIpProtocolScopeValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) IpProtocolScopeValue {
	object, diags := NewIpProtocolScopeValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewIpProtocolScopeValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t IpProtocolScopeType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewIpProtocolScopeValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewIpProtocolScopeValueUnknown(), nil
	}

	if in.IsNull() {
		return NewIpProtocolScopeValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewIpProtocolScopeValueMust(IpProtocolScopeValue{}.AttributeTypes(ctx), attributes), nil
}

func (t IpProtocolScopeType) ValueType(ctx context.Context) attr.Value {
	return IpProtocolScopeValue{}
}

var _ basetypes.ObjectValuable = IpProtocolScopeValue{}

type IpProtocolScopeValue struct {
	IpVersion basetypes.StringValue `tfsdk:"ip_version"`
	state     attr.ValueState
}

func (v IpProtocolScopeValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["ip_version"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.IpVersion.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip_version"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v IpProtocolScopeValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v IpProtocolScopeValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v IpProtocolScopeValue) String() string {
	return "IpProtocolScopeValue"
}

func (v IpProtocolScopeValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"ip_version": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"ip_version": v.IpVersion,
		})

	return objVal, diags
}

func (v IpProtocolScopeValue) Equal(o attr.Value) bool {
	other, ok := o.(IpProtocolScopeValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.IpVersion.Equal(other.IpVersion) {
		return false
	}

	return true
}

func (v IpProtocolScopeValue) Type(ctx context.Context) attr.Type {
	return IpProtocolScopeType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v IpProtocolScopeValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"ip_version": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = MetadataType{}

type MetadataType struct {
	basetypes.ObjectType
}

func (t MetadataType) Equal(o attr.Type) bool {
	other, ok := o.(MetadataType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MetadataType) String() string {
	return "MetadataType"
}

func (t MetadataType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	originAttribute, ok := attributes["origin"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`origin is missing from object`)

		return nil, diags
	}

	originVal, ok := originAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`origin expected to be basetypes.StringValue, was: %T`, originAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return MetadataValue{
		Origin: originVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewMetadataValueNull() MetadataValue {
	return MetadataValue{
		state: attr.ValueStateNull,
	}
}

func NewMetadataValueUnknown() MetadataValue {
	return MetadataValue{
		state: attr.ValueStateUnknown,
	}
}

func NewMetadataValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MetadataValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MetadataValue Attribute Value",
				"While creating a MetadataValue value, a missing attribute value was detected. "+
					"A MetadataValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetadataValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MetadataValue Attribute Type",
				"While creating a MetadataValue value, an invalid attribute value was detected. "+
					"A MetadataValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetadataValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MetadataValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MetadataValue Attribute Value",
				"While creating a MetadataValue value, an extra attribute value was detected. "+
					"A MetadataValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MetadataValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewMetadataValueUnknown(), diags
	}

	originAttribute, ok := attributes["origin"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`origin is missing from object`)

		return NewMetadataValueUnknown(), diags
	}

	originVal, ok := originAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`origin expected to be basetypes.StringValue, was: %T`, originAttribute))
	}

	if diags.HasError() {
		return NewMetadataValueUnknown(), diags
	}

	return MetadataValue{
		Origin: originVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewMetadataValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MetadataValue {
	object, diags := NewMetadataValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewMetadataValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MetadataType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewMetadataValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewMetadataValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMetadataValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewMetadataValueMust(MetadataValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MetadataType) ValueType(ctx context.Context) attr.Value {
	return MetadataValue{}
}

var _ basetypes.ObjectValuable = MetadataValue{}

type MetadataValue struct {
	Origin basetypes.StringValue `tfsdk:"origin"`
	state  attr.ValueState
}

func (v MetadataValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["origin"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Origin.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["origin"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MetadataValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MetadataValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MetadataValue) String() string {
	return "MetadataValue"
}

func (v MetadataValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"origin": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"origin": v.Origin,
		})

	return objVal, diags
}

func (v MetadataValue) Equal(o attr.Value) bool {
	other, ok := o.(MetadataValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Origin.Equal(other.Origin) {
		return false
	}

	return true
}

func (v MetadataValue) Type(ctx context.Context) attr.Type {
	return MetadataType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MetadataValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"origin": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ScheduleType{}

type ScheduleType struct {
	basetypes.ObjectType
}

func (t ScheduleType) Equal(o attr.Type) bool {
	other, ok := o.(ScheduleType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ScheduleType) String() string {
	return "ScheduleType"
}

func (t ScheduleType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	modeAttribute, ok := attributes["mode"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`mode is missing from object`)

		return nil, diags
	}

	modeVal, ok := modeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`mode expected to be basetypes.StringValue, was: %T`, modeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ScheduleValue{
		Mode:  modeVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewScheduleValueNull() ScheduleValue {
	return ScheduleValue{
		state: attr.ValueStateNull,
	}
}

func NewScheduleValueUnknown() ScheduleValue {
	return ScheduleValue{
		state: attr.ValueStateUnknown,
	}
}

func NewScheduleValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ScheduleValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ScheduleValue Attribute Value",
				"While creating a ScheduleValue value, a missing attribute value was detected. "+
					"A ScheduleValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScheduleValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ScheduleValue Attribute Type",
				"While creating a ScheduleValue value, an invalid attribute value was detected. "+
					"A ScheduleValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScheduleValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ScheduleValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ScheduleValue Attribute Value",
				"While creating a ScheduleValue value, an extra attribute value was detected. "+
					"A ScheduleValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ScheduleValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewScheduleValueUnknown(), diags
	}

	modeAttribute, ok := attributes["mode"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`mode is missing from object`)

		return NewScheduleValueUnknown(), diags
	}

	modeVal, ok := modeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`mode expected to be basetypes.StringValue, was: %T`, modeAttribute))
	}

	if diags.HasError() {
		return NewScheduleValueUnknown(), diags
	}

	return ScheduleValue{
		Mode:  modeVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewScheduleValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ScheduleValue {
	object, diags := NewScheduleValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewScheduleValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ScheduleType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewScheduleValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewScheduleValueUnknown(), nil
	}

	if in.IsNull() {
		return NewScheduleValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewScheduleValueMust(ScheduleValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ScheduleType) ValueType(ctx context.Context) attr.Value {
	return ScheduleValue{}
}

var _ basetypes.ObjectValuable = ScheduleValue{}

type ScheduleValue struct {
	Mode  basetypes.StringValue `tfsdk:"mode"`
	state attr.ValueState
}

func (v ScheduleValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["mode"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Mode.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["mode"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ScheduleValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ScheduleValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ScheduleValue) String() string {
	return "ScheduleValue"
}

func (v ScheduleValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"mode": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"mode": v.Mode,
		})

	return objVal, diags
}

func (v ScheduleValue) Equal(o attr.Value) bool {
	other, ok := o.(ScheduleValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Mode.Equal(other.Mode) {
		return false
	}

	return true
}

func (v ScheduleValue) Type(ctx context.Context) attr.Type {
	return ScheduleType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ScheduleValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"mode": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = SourceType{}

type SourceType struct {
	basetypes.ObjectType
}

func (t SourceType) Equal(o attr.Type) bool {
	other, ok := o.(SourceType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SourceType) String() string {
	return "SourceType"
}

func (t SourceType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	trafficFilterAttribute, ok := attributes["traffic_filter"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`traffic_filter is missing from object`)

		return nil, diags
	}

	trafficFilterVal, ok := trafficFilterAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`traffic_filter expected to be basetypes.ObjectValue, was: %T`, trafficFilterAttribute))
	}

	zoneIdAttribute, ok := attributes["zone_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zone_id is missing from object`)

		return nil, diags
	}

	zoneIdVal, ok := zoneIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zone_id expected to be basetypes.StringValue, was: %T`, zoneIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return SourceValue{
		TrafficFilter: trafficFilterVal,
		ZoneId:        zoneIdVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewSourceValueNull() SourceValue {
	return SourceValue{
		state: attr.ValueStateNull,
	}
}

func NewSourceValueUnknown() SourceValue {
	return SourceValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSourceValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SourceValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SourceValue Attribute Value",
				"While creating a SourceValue value, a missing attribute value was detected. "+
					"A SourceValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SourceValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SourceValue Attribute Type",
				"While creating a SourceValue value, an invalid attribute value was detected. "+
					"A SourceValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SourceValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SourceValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SourceValue Attribute Value",
				"While creating a SourceValue value, an extra attribute value was detected. "+
					"A SourceValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SourceValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSourceValueUnknown(), diags
	}

	trafficFilterAttribute, ok := attributes["traffic_filter"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`traffic_filter is missing from object`)

		return NewSourceValueUnknown(), diags
	}

	trafficFilterVal, ok := trafficFilterAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`traffic_filter expected to be basetypes.ObjectValue, was: %T`, trafficFilterAttribute))
	}

	zoneIdAttribute, ok := attributes["zone_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zone_id is missing from object`)

		return NewSourceValueUnknown(), diags
	}

	zoneIdVal, ok := zoneIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zone_id expected to be basetypes.StringValue, was: %T`, zoneIdAttribute))
	}

	if diags.HasError() {
		return NewSourceValueUnknown(), diags
	}

	return SourceValue{
		TrafficFilter: trafficFilterVal,
		ZoneId:        zoneIdVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewSourceValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SourceValue {
	object, diags := NewSourceValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewSourceValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SourceType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSourceValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSourceValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSourceValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSourceValueMust(SourceValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SourceType) ValueType(ctx context.Context) attr.Value {
	return SourceValue{}
}

var _ basetypes.ObjectValuable = SourceValue{}

type SourceValue struct {
	TrafficFilter basetypes.ObjectValue `tfsdk:"traffic_filter"`
	ZoneId        basetypes.StringValue `tfsdk:"zone_id"`
	state         attr.ValueState
}

func (v SourceValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["traffic_filter"] = basetypes.ObjectType{
		AttrTypes: TrafficFilterValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["zone_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.TrafficFilter.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["traffic_filter"] = val

		val, err = v.ZoneId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["zone_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SourceValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SourceValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SourceValue) String() string {
	return "SourceValue"
}

func (v SourceValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var trafficFilter basetypes.ObjectValue

	if v.TrafficFilter.IsNull() {
		trafficFilter = types.ObjectNull(
			TrafficFilterValue{}.AttributeTypes(ctx),
		)
	}

	if v.TrafficFilter.IsUnknown() {
		trafficFilter = types.ObjectUnknown(
			TrafficFilterValue{}.AttributeTypes(ctx),
		)
	}

	if !v.TrafficFilter.IsNull() && !v.TrafficFilter.IsUnknown() {
		trafficFilter = types.ObjectValueMust(
			TrafficFilterValue{}.AttributeTypes(ctx),
			v.TrafficFilter.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"traffic_filter": basetypes.ObjectType{
			AttrTypes: TrafficFilterValue{}.AttributeTypes(ctx),
		},
		"zone_id": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"traffic_filter": trafficFilter,
			"zone_id":        v.ZoneId,
		})

	return objVal, diags
}

func (v SourceValue) Equal(o attr.Value) bool {
	other, ok := o.(SourceValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.TrafficFilter.Equal(other.TrafficFilter) {
		return false
	}

	if !v.ZoneId.Equal(other.ZoneId) {
		return false
	}

	return true
}

func (v SourceValue) Type(ctx context.Context) attr.Type {
	return SourceType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SourceValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"traffic_filter": basetypes.ObjectType{
			AttrTypes: TrafficFilterValue{}.AttributeTypes(ctx),
		},
		"zone_id": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = TrafficFilterType{}

type TrafficFilterType struct {
	basetypes.ObjectType
}

func (t TrafficFilterType) Equal(o attr.Type) bool {
	other, ok := o.(TrafficFilterType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TrafficFilterType) String() string {
	return "TrafficFilterType"
}

func (t TrafficFilterType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TrafficFilterValue{
		TrafficFilterType: typeVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewTrafficFilterValueNull() TrafficFilterValue {
	return TrafficFilterValue{
		state: attr.ValueStateNull,
	}
}

func NewTrafficFilterValueUnknown() TrafficFilterValue {
	return TrafficFilterValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTrafficFilterValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TrafficFilterValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TrafficFilterValue Attribute Value",
				"While creating a TrafficFilterValue value, a missing attribute value was detected. "+
					"A TrafficFilterValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TrafficFilterValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TrafficFilterValue Attribute Type",
				"While creating a TrafficFilterValue value, an invalid attribute value was detected. "+
					"A TrafficFilterValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TrafficFilterValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TrafficFilterValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TrafficFilterValue Attribute Value",
				"While creating a TrafficFilterValue value, an extra attribute value was detected. "+
					"A TrafficFilterValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TrafficFilterValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTrafficFilterValueUnknown(), diags
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewTrafficFilterValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewTrafficFilterValueUnknown(), diags
	}

	return TrafficFilterValue{
		TrafficFilterType: typeVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewTrafficFilterValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TrafficFilterValue {
	object, diags := NewTrafficFilterValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTrafficFilterValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TrafficFilterType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTrafficFilterValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTrafficFilterValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTrafficFilterValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTrafficFilterValueMust(TrafficFilterValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TrafficFilterType) ValueType(ctx context.Context) attr.Value {
	return TrafficFilterValue{}
}

var _ basetypes.ObjectValuable = TrafficFilterValue{}

type TrafficFilterValue struct {
	TrafficFilterType basetypes.StringValue `tfsdk:"type"`
	state             attr.ValueState
}

func (v TrafficFilterValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.TrafficFilterType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TrafficFilterValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TrafficFilterValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TrafficFilterValue) String() string {
	return "TrafficFilterValue"
}

func (v TrafficFilterValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"type": v.TrafficFilterType,
		})

	return objVal, diags
}

func (v TrafficFilterValue) Equal(o attr.Value) bool {
	other, ok := o.(TrafficFilterValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.TrafficFilterType.Equal(other.TrafficFilterType) {
		return false
	}

	return true
}

func (v TrafficFilterValue) Type(ctx context.Context) attr.Type {
	return TrafficFilterType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TrafficFilterValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"type": basetypes.StringType{},
	}
}
